################
### Language ###
################
language: bash

services:
  - docker

#####################
### Notifications ###
#####################
notifications:
  email: false

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

matrix:
  include:
  - env: PAPER_VERSION=1.18.2 PAPER_BUILD=317 JAVA_VERSION=17
