version: '3.7'

services:
  papermc_server:
    image: kunihir0/papermc_arch:1.18.2
    container_name: papermc_server
    stdin_open: true
    tty: true
    restart: always
    networks:
      - papermc_server
    ports:
      - 25565:25565
    volumes:
      - minecraft-config:/opt/minecraft/config
      - minecraft-worlds:/opt/minecraft/worlds
      - minecraft-plugins:/opt/minecraft/plugins
      - minecraft-data:/opt/minecraft/data
      - minecraft-logs:/opt/minecraft/logs

volumes:
  minecraft-config: {}
  minecraft-worlds: {}
  minecraft-plugins: {}
  minecraft-data: {}
  minecraft-logs: {}

networks:
  papermc_server: {}
